### ISSUE TITLE
Add list of all data contributors 

### ISSUE THREAD

**Issue by chrissyrissmeyer** [clirdlf/digitization_cost_calculator#24]
It would be great to acknowledge all of the institutions who have contributed data to the calculator over the years regardless of whether or not that data is in the current version of the calculator. 

The list of contributors should be added to the [About](http://dashboard.diglib.org/about/) page after the Contact Us section. (text below)

## Contributing Institutions

Thank you to all of the institutions who have contributed data for past and present versions of the calculator! The Cost Calculator would not exist without the contributions from our community. Note that not all contributions are integrated into the current cost calculator due to issues with data definitions, methods for tracking data, and changing needs of the calculator.

----------------------
**Tasks**
- [x] Identify appropriate location on calculator website for the list
- [x] Create the list of institutions
- [x] Wordsmith brief acknowledgement statement

**Comment by chrissyrissmeyer** [comment]
List of contributors is here: https://docs.google.com/spreadsheets/d/1-_zOl_9aPFEe1yJlfLBftiJjkb5olJY9TRT1LcMl__Y/edit#gid=1690188289

Please let me know if I need to move it to a better location, etc.
